config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'

  resources :companies do
    resources :employees
  end

  root 'welcome#index'

  get 'companies/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
  accepts_nested_attributes_for :employees
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  belongs_to :company
  validates :forename, :surname, :middlename, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController

  def index
    @company = Company.all
  end

  def show
    @company = Company.find(permitted_params[:id])
    @company = Company.first
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(permitted_params[:company])

    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def destroy
    @company = Company.find(permitted_params[:id])
    @company.destroy

    redirect_to companies_path
  end

  private

  def permitted_params
    params.permit!
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :find_company
  before_action :set_employee, only: %i[show edit update destroy]

  def index
    @employees = @company.employees
  end

  def show; end

  def new
    @employee = @company.employees.build
  end

  def edit; end

  def create
    @employee = @company.employees.build(permitted_params[:employee])
    if @employee.save
      redirect_to company_employees_path(@company)
    else
      render 'new'
    end
  end

  def update
    if @employee.update(forename: permitted_params[:forename],
                        surname: permitted_params[:surname])
      redirect_to company_employees_path(@company)
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to company_employees_path(@company)
  end

  private

  def set_employee
    @employee = Employee.find(permitted_params[:id])
  end

  def permitted_params
    params.permit!
  end

  def find_company
    @company = Company.find(permitted_params[:company_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/index.html.erb
<h2 class="pb-2">Listing Companies</h2>

<table class="table table-striped">
  <thead>

    <tr>
      <th>ID</th>
      <th>Company Name</th>
      <th>Details</th>
      <th class="text-center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @company.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= company.name %></td>
        <td><%= company.details %></td>
        <td class="text-center">
          <%= link_to "Show", company_path(company), class: "btn btn-primary btn-sm"%>
          <%= link_to "Destroy", company_path(company), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create New Company", new_company_path, class: "btn btn-primary" %>

app/views/companies/new.html.erb
<h2 class="pb-2">New Company</h2>

<%= form_with scope: :company, url: companies_path, local: true do |form| %>

<% if @company.errors.any? %>
  <div id="error">
    <h2 class="pb-2">
      <%= pluralize(@company.errors.count, "error") %>
      prohibited this employee from being saved:
    </h2>
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

<% end %>

<p>
  <form>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>

      <p>
        <%= form.label :details %>
        <%= form.text_area :details, class: "form-control" %>
      </p>

      <p>
        <button type="submit" class="btn btn-primary">Save</button>
        <%= link_to "Back to companies list", companies_path, class: "btn btn-outline-primary", role: "button" %>
      </p>
    <% end %>

  </div>

app/views/companies/show.html.erb
<h3><%= @company.name %></h3>
<p><%= @company.details %></p>

<h3>Employees</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Forename</th>
      <th>Surname</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% for employee in @company.employees %>
      <tr>
        <td><%= employee.id %></td>
        <td><%= employee.forename %></td>
        <td><%= employee.surname %></td>
        <td><%= link_to "Edit", edit_company_employee_path(employee), class: "btn btn-primary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add Employee", new_company_employee_path(@company), class: "btn btn-primary" %>

<%= link_to "Back to companies List", companies_path, class: "btn btn-outline-primary" %>

app/views/employees/edit.html.erb
<h2 class="pb-2">Edit Employee</h2>

<%= form_with(model: @employees, url: :company_employee ,method: :put, local: true) do |form| %>

<% if @employee.errors.any? %>
  <div id="error_explanation">
    <h2 class="pb-2">
      <%= pluralize(@employee.errors.count, "error") %>
      prohibited this employee from being saved:
    </h2>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :forename %>
  <%= form.text_field :forename, :value => @employee.forename, class: "form-control" %>

  <p>
    <%= form.label :surname %>
    <%= form.text_field :surname, :value => @employee.surname, class: "form-control" %>
  </p>

  <p>
    <button type="submit" class="btn btn-primary remote: true">Save</button>
    <%= link_to "Back to employees list", company_employees_path(@company), class: "btn btn-outline-primary" %>
  </p>
<% end %>


</div>

app/views/employees/index.html.erb
<h2 class="pb-2">Listing Employees</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Company</th>
      <th>Forename</th>
      <th>Surname</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee|%>
      <tr>
        <td><%= link_to employee.id, company_employee_path(@company, employee) %></td>
        <td><%= link_to employee.company.name, [@company] %></td>
        <td><%= employee.forename %></td>
        <td><%= employee.surname %></td>
        <td>
          <%= link_to "Edit Employee", edit_company_employee_path(@company, employee), class: "btn btn-primary btn-sm" %>
          <%= link_to "Destroy Employee", [@company, employee], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= link_to "Create New Employee", new_company_employee_path(@company), class: "btn btn-primary" %>

app/views/employees/new.html.erb
<h2 class="pb-2">New Employee</h2>

<%= form_with(model: [@company, @employee], local: true) do |form| %>

<% if @employee.errors.any? %>
  <div id="error_explanation">
    <h2 class="pb-2">
      <%= pluralize(@employee.errors.count, "error") %>
      prohibited this employee from being saved:
    </h2>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <div class="form-group">
    <%= form.label :forename %>
    <%= form.text_field :forename, class: "form-control" %>

    <p>
      <%= form.label :surname %>
      <%= form.text_field :middlename, class: "form-control" %>
    </p>

    <p>
      <button type="submit" class="btn btn-primary">Save</button>
      <%= link_to "Back to employees list", company_employees_path(@company), class: "btn btn-primary" %>
    </p>
  <% end %>


</div>

app/views/employees/show.html.erb
<p>
  <strong>Forename:</strong>
  <%= @employee.forename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @employee.surname %>
</p>

<%= link_to "Edit", edit_company_employee_path(@company, @employee), class: "btn btn-primary" %>

<%= link_to "Back to employees List", company_employees_path(@company), class: "btn btn-outline-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary border-1 border-bottom border-light">
      <%= link_to root_path, class: "navbar-brand" do %>
      <img src="/images/smart-logo.svg" height="40" alt="smart-logo">
    <% end %>
  </nav>
  <div class="container mt-4">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<h2 class="pb-2">Welcome to the app</h2>
<%= link_to "Create New Company", new_company_path, class: "btn btn-primary" %>
<%= link_to "Companies list", companies_path, class: "btn btn-outline-primary", role: "button" %>